### ISSUE TITLE
Unable to use linkTo() inside a function

### ISSUE THREAD

**Issue by iansoper** [storybooks/storybook-addon-links#21]
when I try to use the linkTo function inside of a handleClick function, it doesn't work. It only works when directly inside of a onClick prop. Examples:

Not Working:

``` jsx

class MainHeader extends React.Component {

  handleClick = (e, { name, index } ) => {
    linkTo('Home', 'default');
    action('Header Link')( name );
  };

  render() {
    return (
      <Component onClick={ this.handleClick } />
    )
  }
}
```

Working:

``` jsx

class MainHeader extends React.Component { 
  render() {
    return (
      <Component onClick={ linkTo('Home', 'default'); } />
    )
  }
}
```

**Comment by arunoda** [comment]
`linkTo` function returns a callback. It did a log in the ActionLogger, when you called that callback.
Anyway, you should not use `linkTo`, `action` or any storybook related stuff inside your app's components.
